inotify:
  image: 'pstauffer/inotify:latest'
  container_name: 'inotify'

  volumes:
  - '/var/run/docker.sock:/tmp/docker.sock:ro'
  - '/var/lib/docker/data/bind/config:/config'
  - '/var/lib/docker/data/bind/data:/data'

  environment:
  - 'CONTAINER=bind'
  - 'VOLUMES=/config /data'

  restart: always
